name: sphere_book
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  go_router: ^14.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/GT Sectra Fine Regular.ttf

